[package]
edition      = "2024"
name         = "exif-beam"
rust-version = "1.88"
version      = "0.1.0"


[[test]]
harness = false
name    = "hello_test"

[dependencies]
esp-hal = { git = "https://github.com/esp-rs/esp-hal", features = ["defmt", "esp32s3", "unstable"] }

esp-rtos = { git = "https://github.com/esp-rs/esp-hal", features = [
  "defmt",
  "embassy",
  "esp-alloc",
  "esp-radio",
  "esp32s3",
] }
esp-bootloader-esp-idf = { git = "https://github.com/esp-rs/esp-hal", features = ["defmt", "esp32s3"] }


# Logging
defmt = "1.0.1"

# use these two for espflash
esp-println = { git = "https://github.com/esp-rs/esp-hal", features = ["defmt-espflash", "esp32s3"] }
esp-backtrace = { git = "https://github.com/esp-rs/esp-hal", features = ["defmt", "esp32s3", "panic-handler"] }

# Use this for probe-rs
#panic-rtt-target = { version = "0.2.0", features = ["defmt"] }
#rtt-target = { version = "0.6.2", features = ["defmt"] }


# Embassy
embassy-executor = { version = "0.10.0", features = ["defmt"] }
embassy-sync = "0.8.0"
embassy-time = { version = "0.5.0", features = ["defmt"] }
embassy-futures = "0.1.2"
embassy-embedded-hal = "0.6.0"

# Embedded IO
embedded-io = { version = "0.7.1", features = ["defmt"] }
embedded-io-async = { version = "0.7.0", features = ["defmt"] }

# Memory
esp-alloc = { git = "https://github.com/esp-rs/esp-hal", features = ["defmt"] }
allocator-api2 = { version = "0.3", default-features = false, features = ["alloc"] }

# Bluetooth
esp-radio = { git = "https://github.com/esp-rs/esp-hal", features = [
  "ble",
  "defmt",
  "esp-alloc",
  "esp32s3",
  "unstable",
] }
trouble-host = { version = "0.7.0", features = ["gatt", "security", "scan", "legacy-pairing", "defmt"] }
bt-hci = "0.9.0"

# Memory stuff and such
critical-section = "1.2.0"
static_cell      = "2.1.1"
heapless = "0.9.3"
chrono = { version = "0.4.43", default-features = false }
embedded-hal-compat = "0.13.0"

# Graphics
embedded-graphics = "0.8.2"

# Protocol crates
ublox = { version = "0.10", default-features = false, features = ["ubx_proto31", "alloc"] }
nmea = {version = "0.7.0", default-features = false, features = ["GNSS", "defmt-03"]}

# Hardware peripherals
axp2101-dd = { git = "https://github.com/FlareFlo/axp2101-dd.git", branch = "main" } # PMU
oled_async = { git = "https://github.com/techmccat/sh1106.git", branch = "master"} # Display
display-interface-i2c = "0.5"

# Timezone stuff
# Spatial: Drop historical borders, use grid compression
trtz = { version = "0.1.1", default-features = false, features = ["variant-now", "grid-scale-4"] }

# Temporal Database: Embedded IANA tables
tzdb = { version = "0.7.3", default-features = false }

[dev-dependencies]
embedded-test = { version = "0.7.1", features = [
  "defmt",
  "embassy-010",
  "external-executor",
  "xtensa-semihosting",
] }

# For fine tuning these settings, please refer to https://doc.rust-lang.org/cargo/reference/profiles.html
[profile.dev]
# The default debug profile is too slow and too big for resource-constrained devices.
# Always build with some optimizations enabled.
opt-level = "s"

[profile.release]
codegen-units = 1     # LLVM can perform better optimizations using a single thread
debug         = 2     # prefer slower builds but better debugging experience
lto           = 'fat'
opt-level     = 's'
